<?php

/**
 * BaseTerminationReason
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property EmployeeTerminationRecord $EmployeeTerminationRecord
 * 
 * @method integer                   getId()                        Returns the current record's "id" value
 * @method string                    getName()                      Returns the current record's "name" value
 * @method EmployeeTerminationRecord getEmployeeTerminationRecord() Returns the current record's "EmployeeTerminationRecord" value
 * @method TerminationReason         setId()                        Sets the current record's "id" value
 * @method TerminationReason         setName()                      Sets the current record's "name" value
 * @method TerminationReason         setEmployeeTerminationRecord() Sets the current record's "EmployeeTerminationRecord" value
 * 
 * @package    orangehrm
 * @subpackage model\pim\base
 * @author     Maheswar Reddy && Chandra Sekhar 
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseExpenseType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_emp_expense_type');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
    }

    // public function setUp()
    // {
    //     parent::setUp();
    //     $this->hasOne('EmployeeTerminationRecord', array(
    //          'local' => 'id',
    //          'foreign' => 'reasonId'));
    // }
}