<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/03/20 12:57:30

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=172.16.1.29;port=3306;dbname=sunhrm',
  'username' => 'sunhrm',
  'password' => 'H&3ss83^3#@i',
  'attributes' => 
  array (
    'export' => 'tables',
  ),
  'name' => 'doctrine',
)),);
