<?php

/**
 * BaseProjectAdmin
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $projectId
 * @property integer $empNumber
 * @property Project $Project
 * @property Employee $Employee
 * 
 * @method integer      getProjectId() Returns the current record's "projectId" value
 * @method integer      getEmpNumber() Returns the current record's "empNumber" value
 * @method Project      getProject()   Returns the current record's "Project" value
 * @method Employee     getEmployee()  Returns the current record's "Employee" value
 * @method ProjectAdmin setProjectId() Sets the current record's "projectId" value
 * @method ProjectAdmin setEmpNumber() Sets the current record's "empNumber" value
 * @method ProjectAdmin setProject()   Sets the current record's "Project" value
 * @method ProjectAdmin setEmployee()  Sets the current record's "Employee" value
 * 
 * @package    orangehrm
 * @subpackage model\admin\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCostCenterMapping extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cost_center_mapping');
        $this->hasColumn('id as id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('costcenter_id as costCenterId', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
         $this->hasColumn('location as location', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('empId as empId', 'string', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));  
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CostCenter', array(
             'local' => 'costcenter_id',
             'foreign' => 'id'));

        // $this->hasMany('Employee', array(
        //      'local' => 'empId',
        //      'foreign' => 'emp_number'));

        // $this->hasOne('Location', array(
        //      'local' => 'location',
        //      'foreign' => 'id'));
    }
}